version: "2"

formatters:
  enable:
    - gofumpt
    - goimports

linters:
  enable:
    - goconst
    - gocritic
    - gosec
    - misspell
    - staticcheck

  exclusions:
    rules:
      - linters:
          - goconst
          - gosec
        path: _test\.go
